
[STEP1]ユーザーログイン前のテスト
  トップページのテスト：ログインしていない状態
    表示内容の確認
[31m      URLが正しい (FAILED - 1)[0m
[31m      main-visualが表示される (FAILED - 2)[0m
[31m      人気の投稿が表示される (FAILED - 3)[0m

Failures:

  1) [STEP1]ユーザーログイン前のテスト トップページのテスト：ログインしていない状態 表示内容の確認 URLが正しい
     [31mGot 0 failures and 2 other errors:[0m

     1.1) [31mFailure/Error: [0mvisit root_path[0m
          [31m[0m
          [31mSelenium::WebDriver::Error::WebDriverError:[0m
          [31m  unable to connect to /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/chromedriver-helper-2.1.1/bin/chromedriver-helper 127.0.0.1:9515[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:54:in `start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service.rb:84:in `launch'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:374:in `service_url'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:74:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver.rb:88:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'[0m
          [36m# ./spec/system/01_before_login_spec.rb:13:in `block (3 levels) in <top (required)>'[0m

     1.2) [31mFailure/Error: [0mraise [1;34;4mError[0m::[1;34;4mWebDriverError[0m, cannot_connect_error_text[0m
          [31m[0m
          [31mSelenium::WebDriver::Error::WebDriverError:[0m
          [31m  unable to connect to /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/chromedriver-helper-2.1.1/bin/chromedriver-helper 127.0.0.1:9515[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:54:in `start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service.rb:84:in `launch'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:374:in `service_url'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:74:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver.rb:88:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'[0m

  2) [STEP1]ユーザーログイン前のテスト トップページのテスト：ログインしていない状態 表示内容の確認 main-visualが表示される
     [31mGot 0 failures and 2 other errors:[0m

     2.1) [31mFailure/Error: [0mvisit root_path[0m
          [31m[0m
          [31mSelenium::WebDriver::Error::WebDriverError:[0m
          [31m  unable to connect to /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/chromedriver-helper-2.1.1/bin/chromedriver-helper 127.0.0.1:9515[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:54:in `start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service.rb:84:in `launch'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:374:in `service_url'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:74:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver.rb:88:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'[0m
          [36m# ./spec/system/01_before_login_spec.rb:13:in `block (3 levels) in <top (required)>'[0m

     2.2) [31mFailure/Error: [0mraise [1;34;4mError[0m::[1;34;4mWebDriverError[0m, cannot_connect_error_text[0m
          [31m[0m
          [31mSelenium::WebDriver::Error::WebDriverError:[0m
          [31m  unable to connect to /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/chromedriver-helper-2.1.1/bin/chromedriver-helper 127.0.0.1:9515[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:54:in `start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service.rb:84:in `launch'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:374:in `service_url'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:74:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver.rb:88:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'[0m

  3) [STEP1]ユーザーログイン前のテスト トップページのテスト：ログインしていない状態 表示内容の確認 人気の投稿が表示される
     [31mGot 0 failures and 2 other errors:[0m

     3.1) [31mFailure/Error: [0mvisit root_path[0m
          [31m[0m
          [31mSelenium::WebDriver::Error::WebDriverError:[0m
          [31m  unable to connect to /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/chromedriver-helper-2.1.1/bin/chromedriver-helper 127.0.0.1:9515[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:54:in `start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service.rb:84:in `launch'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:374:in `service_url'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:74:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver.rb:88:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'[0m
          [36m# ./spec/system/01_before_login_spec.rb:13:in `block (3 levels) in <top (required)>'[0m

     3.2) [31mFailure/Error: [0mraise [1;34;4mError[0m::[1;34;4mWebDriverError[0m, cannot_connect_error_text[0m
          [31m[0m
          [31mSelenium::WebDriver::Error::WebDriverError:[0m
          [31m  unable to connect to /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/chromedriver-helper-2.1.1/bin/chromedriver-helper 127.0.0.1:9515[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service_manager.rb:54:in `start'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/service.rb:84:in `launch'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:374:in `service_url'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:74:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver/common/driver.rb:47:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.0.3/lib/selenium/webdriver.rb:88:in `for'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'[0m
          [36m# /home/ec2-user/.rvm/gems/ruby-2.6.3/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'[0m

Finished in 2 minutes 0.5 seconds (files took 1.11 seconds to load)
[31m3 examples, 3 failures[0m

Failed examples:

[31mrspec ./spec/system/01_before_login_spec.rb:17[0m [36m# [STEP1]ユーザーログイン前のテスト トップページのテスト：ログインしていない状態 表示内容の確認 URLが正しい[0m
[31mrspec ./spec/system/01_before_login_spec.rb:20[0m [36m# [STEP1]ユーザーログイン前のテスト トップページのテスト：ログインしていない状態 表示内容の確認 main-visualが表示される[0m
[31mrspec ./spec/system/01_before_login_spec.rb:23[0m [36m# [STEP1]ユーザーログイン前のテスト トップページのテスト：ログインしていない状態 表示内容の確認 人気の投稿が表示される[0m

